version: '3.9'
services:
  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: ${OLLAMA_BASE_URL:-http://localhost:11434}
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - '44444:8080'
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
      - SCARF_NO_ANALYTICS=${SCARF_NO_ANALYTICS:-true}
      - DO_NOT_TRACK=${DO_NOT_TRACK:-true}
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-false}
    restart: unless-stopped

  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    volumes:
      - pipelines:/app/pipelines
    ports:
      - :9099
    restart: always

volumes:
  open-webui: {}
  pipelines: {}
